openapi: 3.0.0
info:
  title: Simple Service
  description: API documentation for Simple Service project
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Local development server

paths:
  /v1/create_task:
    post:
      summary: Create a new task
      description: Creates a new task in the system.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
              properties:
                title:
                  type: string
                  example: "Implement new feature"
                description:
                  type: string
                  example: "Develop a new API endpoint for user management"
      responses:
        "200":
          description: Task created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  data:
                    type: object
                    properties:
                      task_id:
                        type: integer
                        example: 1
        "400":
          description: Invalid request format
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  error:
                    type: object
                    properties:
                      code:
                        type: string
                        example: "FIELD_INCORRECT"
                      desc:
                        type: string
                        example: "Invalid request body"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  error:
                    type: object
                    properties:
                      code:
                        type: string
                        example: "SERVICE_UNAVAILABLE"
                      desc:
                        type: string
                        example: "Service is currently unavailable. Please try again later."
  /v1/tasks/{id}:
    get:
      summary: Get task by ID
      description: Retrieves a task by its ID.
      parameters:
        - name: id
          in: path
          required: true
          description: Task ID
          schema:
            type: integer
            example: 1
      responses:
        "200":
          description: Task retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      title:
                        type: string
                        example: "Implement new feature"
                      description:
                        type: string
                        example: "Develop a new API endpoint for user management"
                      status:
                        type: string
                        example: "new"
                      created_at:
                        type: string
                        format: date-time
                        example: "2024-01-15T10:30:00Z"
                      updated_at:
                        type: string
                        format: date-time
                        example: "2024-01-15T10:30:00Z"
        "400":
          description: Invalid task ID
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  error:
                    type: object
                    properties:
                      code:
                        type: string
                        example: "FIELD_INCORRECT"
                      desc:
                        type: string
                        example: "Invalid task ID"
        "404":
          description: Task not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  error:
                    type: object
                    properties:
                      code:
                        type: string
                        example: "NOT_FOUND"
                      desc:
                        type: string
                        example: "Task not found"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  error:
                    type: object
                    properties:
                      code:
                        type: string
                        example: "SERVICE_UNAVAILABLE"
                      desc:
                        type: string
                        example: "Service is currently unavailable. Please try again later."
