# Конфигурация golangci-lint версии 2.x
version: 2

run:
  timeout: 5m
  go: "1.24"

linters:
  enable:
    - misspell # проверка орфографии
    - gocyclo # цикломатическая сложность
    - dupl # дублирование кода
    - unconvert # ненужные конверсии типов
    - whitespace # лишние пробелы
    - govet # статический анализ
    - ineffassign # неиспользуемые присваивания
    - unused # неиспользуемый код
  disable:
    - revive # отключаем строгие правила документации

linters-settings:
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gocyclo
    - path: "internal/repo/mocks/"
      linters:
        - unused
